name: cRecipes
description: Improved custom recipes for Bukkit servers
version: ${pom.version}-b${BUILD_NUMBER}
main: net.catharos.recipes.cRecipes

author: [SpaceEmotion, dwi]
website: http://www.catharos.de

commands:
  creload:
    description: Reloads the cRecipes plugin config and recipes 
    usage: /<command>